/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.impl;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import presenter.SimplePresenter;
import util.ScreenUtil;
import view.SimpleView;

/**
 *
 * @author eko
 */
public class FrmMain extends javax.swing.JFrame implements SimpleView {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        initListener();
    }
    
    private void initListener() {
        final SimplePresenter presenter = new SimplePresenter(this);
        
        btnProcess.addActionListener((ActionEvent e) -> {
//            presenter.doProcess();

            List<Person> list = new ArrayList() {
                {
                    add(new Person(29, "Eko Suhariyadi"));
                    add(new Person(17, "Nur Huda"));
                    add(new Person(19, "Robert Hayden"));
                }
            };
       
            
            /** imperative style */
//            List<Person> filtered = new ArrayList();
//            for (Person person : list) {
//                if(person.age>17){
//                    filtered.add(person);
//                }
//            }
//            for (Person person : filtered) {
//                System.out.println(person);
//            }
            
            /** functional style */
            list.stream()
                    .filter((Person p) -> p.age > 17)
                    .forEach(System.out::println);
        });
    }
    
    class Person {
        
        private final int age;
        private final String name;
        
        public Person(int age, String name) {
            this.age = age;
            this.name = name;
        }
        
        @Override
        public String toString() {
            return String.format("{age: %d, name: %s}", age, name);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcess = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProcess.setText("Run Process");

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(btnProcess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProcess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmMain().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLog;
    // End of variables declaration//GEN-END:variables

//    @Override
//    public void showLoading() {
//        ScreenUtil.setCursorThinking(this);
//    }
    @Override
    public void hideLoading() {
        ScreenUtil.setCursorDefault(this);
    }
    
    @Override
    public void indicateProcessRunning(int progress) {
        txtLog.insert(String.format("deta ---> %d\n", progress), 0);
    }
}
